version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./storage/prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secretpassword
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./storage/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
